### ISSUE TITLE
Samsung android 12 not Work

### ISSUE THREAD

**Issue by ash737** [leolin310148/ShortcutBadger#378]
Notification badge not work in galaxy M 12 (android 12)
I have targetSdkVersion = 28 in build.gradle but in config.xml  targetSdkVersion equal to 30

Cordova: 11.0.0
Cordova android: 8.1.0

I have tested many android devices, all work fine but, Samsung Galaxy M 12 not work.

Please help

**Comment by ash737** [comment]
@leolin310148

**Comment by ash737** [comment]
I have fixed by add the following in Mainifest.xml
``` <uses-permission android:name="com.sonyericsson.home.permission.BROADCAST_BADGE" />
    <uses-permission android:name="com.sonymobile.home.permission.PROVIDER_INSERT_BADGE" />
    <uses-permission android:name="com.anddoes.launcher.permission.UPDATE_COUNT" />
    <uses-permission android:name="com.majeur.launcher.permission.UPDATE_BADGE" />
    <uses-permission android:name="com.huawei.android.launcher.permission.CHANGE_BADGE" />
    <uses-permission android:name="com.huawei.android.launcher.permission.READ_SETTINGS" />
    <uses-permission android:name="com.huawei.android.launcher.permission.WRITE_SETTINGS" />
    <uses-permission android:name="android.permission.READ_APP_BADGE" />
    <uses-permission android:name="com.oppo.launcher.permission.READ_SETTINGS" />
    <uses-permission android:name="com.oppo.launcher.permission.WRITE_SETTINGS" />
    <uses-permission android:name="me.everything.badger.permission.BADGE_COUNT_READ" />
    <uses-permission android:name="me.everything.badger.permission.BADGE_COUNT_WRITE" />

 ```

Thank you @leolin310148

**Comment by wsilva98** [comment]
Hi, I do have a similar issue in a Samsung S12 android 12, I added what you suggested to the manifest but it still doesn't work... @ash737 @leolin310148 any ideas on how to make this work?

**Comment by rafaelsetragni** [comment]
What is "doesn't work"? Your phone won't boot? Does the badge never appear? Is the badge counter wrong? Are you in the wrong colors? appears otherwise???
Everything possible can be "is not working".

I'm using it on Samsung 12 (S20 FE) right now and "it's working". What I think you're thinking is "not working" is in fact the default of the platform. For Samsung devices using One UI, if there is no notification in the status bar, your badge will not be displayed, but the number counter will still be there. As soon as your app sends a notification to the status bar, the badge is displayed again with its current value.

Oh! Please stop to use "is/not working" expression. We are IT professionals, this is a kind of layman's language, it don't belong to us.

**Comment by wsilva98** [comment]
@rafaelsetragni I'm not sure what OP meant, but on my case clearing the notification counter doesn't seem to work. I'm not very familiar with Samsung devices but it seems as you suggested that until the notification in the notification center (I guess you call it notification status bar) is not cleared, the counter will be displayed. Is this normal behaviour?

**Comment by rafaelsetragni** [comment]
Yes, this is the normal behavior.

**Comment by Antiglobalist** [comment]
I have received next message on Samsung OS 13
 java.lang.SecurityException: Permission Denial: writing com.sec.android.provider.badge.BadgeProvider uri content://com.sec.badge/apps?notify=true from pid=14167, uid=10364 requires com.sec.android.provider.badge.permission.WRITE, or grantUriPermission()
 
 So i have added to Manifest also
<uses-permission android:name="com.sec.android.provider.badge.permission.WRITE" />
